name: Build and push Copybara OCI image

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 1 * * *'

jobs:
  copybara:
    runs-on: ubuntu-20.04
    if: github['ref'] == 'refs/heads/master'

    steps:
      - name: Checkout google/copybara repository
        uses: actions/checkout@v2
        with:
          repository: google/copybara
      - name: Login to Packages Container registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: pacificocean-bot
          password: ${{ secrets.CR_PAT }}
      - name: Build Image
        run: |
          docker build --pull -f "Dockerfile" -t ghcr.io/siberianmh/build-images/copybara:latest .
      - name: Publish image
        run: |
          docker push ghcr.io/siberianmh/build-images/copybara:latest
